[tool.poetry]
name = "object-detection-serving"
version = "1.0.0"
description = "Object Detection serving with oneML and MXNET models"
authors = ["Utt Assoratgoon"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
dynaconf = "^3.2.5"
python-json-logger = "^2.0.7"
opencv-python = "^4.10.0.82"
numpy = "^1.26.4"
protobuf = "^5.27.1"
grpcio = "^1.64.1"
grpcio-reflection = "^1.64.1"
onnxruntime = "^1.22.1"

[tool.poetry.group.dev.dependencies]
pytest = "*"
ruff = "*"
codecov = ">=2.1.13"
pytest-cov = "*"
pytest-html = "*"
grpcio-tools = "^1.64.1"
dvc = {extras = ["gs"], version = "^3.51.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
