# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/object_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "proto/object_detection.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cproto/object_detection.proto\x12\x18grpc.object_detection.v1"6\n\x16ObjectDetectionRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"<\n\x0e\x44\x65tectedObject\x12\x0c\n\x04\x62\x62ox\x18\x01 \x03(\x02\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\t"d\n\x17ObjectDetectionResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x39\n\x07objects\x18\x02 \x03(\x0b\x32(.grpc.object_detection.v1.DetectedObject2\x81\x01\n\x0fObjectDetection\x12n\n\x07\x46orward\x12\x30.grpc.object_detection.v1.ObjectDetectionRequest\x1a\x31.grpc.object_detection.v1.ObjectDetectionResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.object_detection_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_OBJECTDETECTIONREQUEST"]._serialized_start = 58
    _globals["_OBJECTDETECTIONREQUEST"]._serialized_end = 112
    _globals["_DETECTEDOBJECT"]._serialized_start = 114
    _globals["_DETECTEDOBJECT"]._serialized_end = 174
    _globals["_OBJECTDETECTIONRESPONSE"]._serialized_start = 176
    _globals["_OBJECTDETECTIONRESPONSE"]._serialized_end = 276
    _globals["_OBJECTDETECTION"]._serialized_start = 279
    _globals["_OBJECTDETECTION"]._serialized_end = 408
# @@protoc_insertion_point(module_scope)
